<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="st" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">

<head>


<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>Admin 2 - Bootstrap Admin Theme</title>

<jsp:include page="/pages/common/importCss.jsp"></jsp:include>

</head>

<body>

	<jsp:include page="userHeader.jsp"></jsp:include>
	<div id="wrapper">

		<!-- Navigation -->


		<div id="page-wrapper">
		<br>
			<div class="row">
				<div class="col-lg-12">
					<h1 class="page-header">Document</h1>
				</div>
				<!-- /.col-lg-12 -->
			</div>
			<!-- /.row -->

			<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
					</button>
					<a class="navbar-brand">Brand</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active"><a id="documentLink" href="#">Document Information</a></li>
						<li><a id="historyLink" href="#">History</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">Close</a></li>
							</ul></li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container-fluid --> </nav>
			<div id="documentInfo">
			<div class="row">
				<div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">Basic Information</div>
						<div class="panel-body">
							<div class="row">

								<fieldset>
									<div class="col-lg-6">
										<div class="form-group">
											<label>UID</label> <span id="documentId" class="form-control">${document.documentId }</span>
											<p class="help-block">Unique identify number for document will be generated by system.</p>
										</div>

										<label>Amount</label>
										<div class="form-group input-group">
											<span class="input-group-addon"><i class="fa fa-eur"></i> </span> <span type="text" class="form-control">${document.amount }</span>
										</div>
									</div>
									<!-- /.col-lg-6 (nested) -->


									<div class="col-lg-6">
										<div class="form-group">
											<label>Client Name</label> <span class="form-control">${document.client }</span>
											<p class="help-block">Client's name .</p>
										</div>

										<label>Resource</label>
										<div class="form-group input-group">
											<span class="input-group-addon"><i class="fa fa-eur"></i> </span> <span type="text" class="form-control">${document.resource}</span>
										</div>

									</div>
									<!-- /.col-lg-6 (nested) -->

									<div class="col-lg-12">
										<div class="form-group">
											<label>Description</label>
											<textarea class="form-control" rows="3"></textarea>
										</div>
									</div>
								</fieldset>

							</div>
							<!-- /.row (nested) -->
						</div>
						<!-- /.panel-body -->
					</div>
					<!-- /.panel -->
				</div>
				<!-- /.col-lg-12 -->
			</div>
			<!-- /.row -->




			<c:forEach var="item" items="${document.comments}">
				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">${item.author.job }</div>
							<div class="panel-body">
								<div class="row">
									<fieldset id="info2risk">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Notation Risque</label>
												<p class="form-control">${item.notation }</p>
												<p class="help-block">Unique identify number for document will be generated by system.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->



										<div class="col-lg-6">
											<div class="form-group">
												<label>Notice</label>
												<p class="form-control">${item.notice }</p>
												<p class="help-block">Unique identify number for document will be generated by system.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->

										<div class="col-lg-12">
											<div class="form-group">
												<label>Comments</label>
												<div class="form-control">${item.comment }</div>
											</div>
										</div>
									</fieldset>
								</div>
							</div>
						</div>
					</div>
				</div>
			</c:forEach>


			<div class="row" id="commentHide">
				<div class="col-lg-12">
					<st:form method="post" modelAttribute="comment" action="addComment">
						<div class="panel panel-default">
							<div class="panel-heading">${document.responsible.job }</div>
							<div class="panel-body">
								<div class="row">
									<fieldset id="info2risk">
										<div class="col-lg-6">
											<st:input class="hideUrl" path="documentId" value="${document.documentId }"></st:input>
											<div class="form-group">
												<label>Notation Risk</label>
												<st:input class="form-control" path="notation"></st:input>
												<p class="help-block">Unique identify number for document will be generated by system.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->



										<div class="col-lg-6">
											<div class="form-group">
												<label>Notice</label>
												<st:input class="form-control" path="notice"></st:input>
												<p class="help-block">Unique identify number for document will be generated by system.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->

										<div class="col-lg-12">
											<div class="form-group">
												<label>Comments</label>
												<st:textarea class="form-control" rows="3" path="comment"></st:textarea>
											</div>
											<button type="submit" class="btn btn-primary btn-lg pull-right">Save</button>
										</div>
									</fieldset>
								</div>
							</div>
						</div>
					</st:form>
				</div>
			</div>


			<c:if test="${user.userId == document.responsible.userId}">
				<div class="row">
					<div class="col-lg-12 text-center">

						<button id="addComment" type="button" class="btn btn-primary btn-lg">Add Comment</button>
						<button id="transfer" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Transfer Button</button>



					</div>
				</div>
			</c:if>
			<br>
		</div>	
		<!-- /#document Information -->
		
		<div id="historyInfo" class="hideUrl">

				<table class="table table-striped">
					<thead>
						<tr>
							<th>Date</th>
							<th>Step</th>
							<th>Phase</th>
							<th>Responsible</th>
							<th>Decision</th>
							<th>Send to</th>
							<th>Message</th>
						</tr>
					</thead>
					<tbody id="historyBody">


					</tbody>
				</table>

			</div>
		
		
		</div>
		<!-- /#page-wrapper -->



	</div>
	<!-- /#wrapper -->

	<!-- Modal -->
	<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<st:form method="post" modelAttribute="decision" action="/Workflow/document/transfer">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						<h4 class="modal-title" id="myModalLabel">Decision</h4>
					</div>
					<div class="modal-body">

						<div class="row">

							<div class="col-lg-2"></div>
							<!-- /.col-lg-6 (nested) -->


							<div class="col-lg-8">
								<%-- 							<div class="form-group">
								<label class="control-label text-warning" for="inputSuccess">Document Id</label>
								<st:input id="" class="form-control text-warning" path="documentId" value="${document.documentId }" disabled></st:input>
							</div> --%>
								<st:hidden path="documentId" value="${document.documentId }"></st:hidden>
								<div class="form-group">
									<label class="control-label text-warning" for="inputSuccess">Actual step</label>
									<p id="currentStep" class="form-control text-warning">${document.currentStep}</p>
								</div>

								<div class="form-group">
									<label class="control-label text-danger" for="inputSuccess">Decision</label>
									<st:select id="decisionSelect" class="form-control text-danger" path="decisionId">
										<option>--Choose decision--</option>
									</st:select>
								</div>

								<div class="form-group">
									<label class="control-label text-danger" for="inputSuccess">Destination</label>
									<st:select id="destinationSelect" class="form-control text-danger" path="destinationId">
										<option>--Choose destination--</option>
									</st:select>
								</div>

								<div class="form-group">
									<label>Comments</label>
									<st:textarea class="form-control" rows="3" path="comment"></st:textarea>
								</div>
							</div>
							<!-- /.col-lg-6 (nested) -->

							<div class="col-lg-2"></div>

						</div>


					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-primary">Valide</button>
					</div>
				</div>
			</st:form>
		</div>
	</div>



	<script>
		
	$(document).ready(function(){
	    $("#addComment").click(function(){
	        $("#commentHide").show();
	    });
	    
	    $("#transfer").click(function(){
	    	
	    	var step = $("#currentStep").text();
	    	var id = step.split("-")[0];
	        $.ajax({url: "/Workflow/workflow/getDecisionByStepId/"+id, success: function(result){
	        	$.each( result, function( index, value ){
		        	$("#decisionSelect").append($('<option>', {
		        	    value: value.keyy,
		        	    text: value.value
		        	}));
	        	});

	        }});
	    });
	    
	    $("#decisionSelect").on("change", function() {
	    	  $("#destinationSelect").empty().append('<option selected="selected" value="0">--Choose destination--</option>');
		        $.ajax({url: "/Workflow/user/getDestinationByStepID/"+this.value, success: function(result){
		        	$.each( result, function( index, value ){
			        	$("#destinationSelect").append($('<option>', {
			        	    value: value.keyy,
			        	    text: value.value
			        	}));
		        	});

		        }});
	    	  
	    	});
	    
	});
	
	var historyFlag = false;
	
	$("#historyLink").click(function(){
 		$("#historyLink").parent().addClass("active");
		$("#historyLink").parent().siblings().removeClass("active");
		var documentId = $("#documentId").text();
		$("#documentInfo").hide();
		if(!historyFlag){
	        $.ajax({url: "/Workflow/document/history/"+documentId, success: function(result){
	        	$.each( result, function( index, value ){
	        		var timee = new Date(value.date);
		        	$("#historyBody").append(
		        			
							"<tr>"+
							"<td>"+timee+"</td>"+
							"<td>"+value.step.stepId+"-"+value.step.stepName+"</td>"+
							"<td>"+value.step.phase+"</td>"+
							"<td>"+value.responsible.userName+"</td>"+
							"<td>"+value.step.decision+"</td>"+
							"<td>"+value.nextResponsible.userName+"</td>"+
							"<td>"+value.message+"</td>"+
							"</tr>"
		        	);
	        	});
	        	historyFlag = true;
	        }});
			
		}

        
        $("#historyInfo").show(1000);
		
	});
	
	$("#documentLink").click(function(){
 		$("#documentLink").parent().addClass("active");
		$("#documentLink").parent().siblings().removeClass("active");
		$("#historyInfo").hide();
		$("#documentInfo").show(1000);
	});
	
	</script>

</body>

</html>
