<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">

<head>


<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>SB Admin 2 - Bootstrap Admin Theme</title>

<jsp:include page="/pages/common/importCss.jsp"></jsp:include>

</head>

<body>

	
	<div id="wrapper">

		<!-- Navigation -->
<jsp:include page="adminHeader.jsp"></jsp:include>

		<div id="page-wrapper">

			
				<div class="row">
					<div class="col-lg-12">
						<h1 class="page-header">Create New User</h1>
					</div>
					<!-- /.col-lg-12 -->
				</div>
				<!-- /.row -->

				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Basic Information</div>
							<div class="panel-body">
								<div class="row">

									<fieldset>
										<div class="col-lg-6">
											<div class="form-group">
												<label>ID</label> <span class="form-control">${user.userId}</span>
												<p class="help-block">User's identify number will be generated by system automatically.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->


										<div class="col-lg-6">
											<div class="form-group">
												<label>User Name</label>
												<span class="form-control">${user.userName}</span>
												<p class="help-block">User's name .</p>
											</div>

										</div>
										<!-- /.col-lg-6 (nested) -->
									</fieldset>

								</div>
								<!-- /.row (nested) -->
							</div>
							<!-- /.panel-body -->
						</div>
						<!-- /.panel -->
					</div>
					<!-- /.col-lg-12 -->
				</div>
				<!-- /.row -->

				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Post information</div>
							<div>
								<div class="panel-body">
									<div class="row">
										<fieldset id="info2modify">
											<div class="col-lg-6">



												<div class="form-group">
													<label for="Select">Site</label>
													<span class="form-control">${user.site}</span>
												</div>

												<div class="form-group">
													<label for="select">agency</label>
													<span class="form-control">${user.agency}</span>
												</div>

												<div id="managerDiv" class="form-group">
													<label>Manager</label>
													<span class="form-control">${user.manager.userId} -- ${user.manager.userName}</span>
													<p class="help-block">You can either tape manager's Id or name, and then choose the manager existing in system.</p>
												</div>


											</div>
											<!-- /.col-lg-6 (nested) -->
											<div class="col-lg-6">


												<div class="form-group">
													<label for="select">Region</label>
													<span class="form-control">${user.region}</span>
												</div>

												<div class="form-group">
													<label for="select">Job</label>
													<span class="form-control">${user.job}</span>
												</div>

												<div id="partnerDiv" class="form-group">
													<label>Partner</label>
													<span class="form-control">${user.partner.userId} -- ${user.partner.userName}</span>
													<p class="help-block">You can either tape partner's Id or name, and then choose the partner existing in system.</p>
													
												</div>

											</div>
											<!-- /.col-lg-6 (nested) -->
										</fieldset>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Another basic Form Elements</div>
							<div>
								<p></p>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12 text-center">

						<button type="button" class="btn btn-primary btn-lg">Modify</button>

					</div>
				</div>
				<br>
			

		</div>
		<!-- /#page-wrapper -->



	</div>
	<!-- /#wrapper -->





</body>

</html>
