<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="st" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">

<head>


<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>Admin 2 - Bootstrap Admin Theme</title>

<jsp:include page="/pages/common/importCss.jsp"></jsp:include>

</head>

<body>

	
	<div id="wrapper">
		<jsp:include page="adminHeader.jsp"></jsp:include>
		<!-- Navigation -->


		<div id="page-wrapper">
		<span>&nbsp;</span>
			
				<div class="row">
					<div class="col-lg-12">
						<h1 class="page-header">Update User's Roles</h1>
					</div>
					<!-- /.col-lg-12 -->
				</div>
				<!-- /.row -->

				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Basic Information</div>
							<div class="panel-body">
								<div class="row">

									<fieldset>
										<div class="col-lg-6">
											<div class="form-group">
												<label>ID</label> <input id="userId" class="form-control" disabled>
												<p class="help-block">User's identify number will be generated by system automatically.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->


										<div class="col-lg-6">
											<div class="form-group">
												<label>User Name</label>
												<input class="form-control" id="userName" />
												<p class="help-block">User's name .</p>
											</div>

										</div>
										<!-- /.col-lg-6 (nested) -->
									</fieldset>

								</div>
								<!-- /.row (nested) -->
							</div>
							<!-- /.panel-body -->
						</div>
						<!-- /.panel -->
					</div>
					<!-- /.col-lg-12 -->
				</div>
				<!-- /.row -->






										<div class="col-lg-5">
											<div class="form-group">
												<label>All Roles can be selected</label>
												<select id="allRoles" multiple="multiple" class="form-control" size="8">
											    </select>
												<p class="help-block">Role description</p>
											</div>
										</div>
										
										
										<div class="col-lg-2">
										<div class="col-lg-offset-5">
											<button type="button" class="btn btn-info btn-md" id="addButton" style="margin-top: 25px;">>></button>
											<br>
											<button type="button" class="btn btn-info btn-md" id="removeButton" style="margin-top: 10px;"><<</button>
										</div>
										</div>
										
										<div class="col-lg-5">
											<div class="form-group">
												<label>Roles in current user</label>
												<select id="currentRoles" multiple="multiple" class="form-control" size="8">

											    </select>
												<p class="help-block">Role description</p>
											</div>
										</div>











				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Another basic Form Elements</div>
							<div>
								
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12 text-center">

						<button id="submitButton" class="btn btn-primary btn-lg">Submit Button</button>

					</div>
				</div>
				<br>
			
		</div>
		<!-- /#page-wrapper -->



	</div>
	<!-- /#wrapper -->






	<script>
		$(document).ready(function() {
			
			function addRemove(){
			    $("#addButton").click(function(){
			        $("#allRoles > option:selected").each(function(){
			            $(this).remove().appendTo("#currentRoles").attr('selected', false);
			        });
			    });

			    $("#removeButton").click(function(){
			        $("#currentRoles > option:selected").each(function(){
			            $(this).remove().appendTo("#allRoles").attr('selected', false);
			        });
			    });
			}
			
			function initRoles(){
				 $.ajax({url: "${pageContext.request.contextPath }/authorization/role", success: function(Roles){
						$.each(Roles, function(i, item) {
							$("#allRoles").append("<option value='" + item.id + "'>" + item.roleName + "</option>");
							
						});
						getUser("${userId}");
				    }});
			}
			
			function getUser(id){
				 $.ajax({url: "${pageContext.request.contextPath }/user/userRole/"+id, success: function(user){
					 	$("#userId").val(user.userId);	
					 	$("#userName").val(user.userName);						
						$.each(user.roles, function(i, item) {
					        $("#allRoles > option").each(function(){
					        	if($(this).val()==item.id)
					            $(this).remove().appendTo("#currentRoles");
					        });
							
						});
				    }});
			};
			
			function updateUserRole(){
				
				var userId = $("#userId").val();	
				
				var roles = new Array(); 
				$("#currentRoles > option").each(function(){
		            var value = $(this).val();
		            roles.push(value);
		        });
				var role = {requestObject : {"userId" : userId, "rolesId" : roles}};

 				$.ajax({
	 					headers: { 
	 				        'Accept': 'application/json',
	 				        'Content-Type': 'application/json' 
	 				    },
	 				   dataType: 'json',
					   url: '${pageContext.request.contextPath }/user/userRole',
					   type: 'PUT',
					   data: JSON.stringify(role),
					   success: function(response) {
							
					   },
	 				   error: function(e) {
	 					    console.log(e);
						},
					});

			};
			
			function init(){
				$("#submitButton").click(function(){
					updateUserRole();
				});
				initRoles();
				addRemove();

			}
			
			init();

		});
	</script>



</body>

</html>
